const faqData = [
    { question: "what is copybot", answer: "CopyBot automatically copies and posts your content from VK to Telegram, saving you time and boosting engagement." },
    { question: "how does copybot work", answer: "CopyBot monitors your VK community and automatically reposts to your Telegram channels." },
    { question: "is copybot free", answer: "CopyBot offers a free trial for one week. After that, affordable plans are available." },
    { question: "how much does copybot cost", answer: "We offer different affordable plans after your free trial period." },
    { question: "can i control copybot", answer: "Yes, you have full control. You can pause or stop autoposting anytime." },
    { question: "what content types are supported", answer: "CopyBot supports text, images, videos, polls, and clips." },
    { question: "can i integrate chatbot on my site", answer: "Yes! Our chatbot can be easily added to any website with just a small embed code." },
    { question: "how to install chatbot", answer: "Installing our chatbot is easy — you just paste a script on your site." },
    { question: "how to contact support", answer: "Contact us via email at mindloop.ai.contact@gmail.com or on Telegram @vkcopybot." },
    { question: "is your service secure", answer: "Yes, we use encrypted connections and follow industry best practices." },
    { question: "hello", answer: "Hi there! 👋 You can ask me about CopyBot features, pricing, how it works, and more." },
    { question: "can you help me", answer: "Sure! Please ask a question about CopyBot, Chatbot, or our services." },
    { question: "i need help", answer: "Sure! Ask me about features, installation, plans, or anything you want." },
    { question: "what is copybot", answer: "CopyBot automatically copies and posts your content from VK to Telegram, saving you time and boosting engagement." },
    { question: "how to try copybot", answer: "You can try CopyBot for free for one week. Just contact us via @vkcopybot on Telegram." },
    { question: "how copybot works", answer: "CopyBot monitors your VK community and automatically reposts to your Telegram channels." },
    { question: "is copybot free", answer: "CopyBot offers a free trial for one week. After that, affordable plans are available." },
    { question: "what content types does copybot support", answer: "CopyBot supports text, images, videos, polls, and clips – in any combination!" },
    { question: "can i control copybot", answer: "Yes, you have full control. You can pause autoposting anytime or add new channels." },
    { question: "hello", answer: "Hi there! 👋 Feel free to ask anything about CopyBot or our Chat Widget!" },
    { question: "hi", answer: "Hello! 👋 I'm here to answer your questions about CopyBot and AI assistants." },
    { question: "how much does copybot cost", answer: "After the free trial, CopyBot offers affordable monthly and yearly plans. Contact us for details!" },
    { question: "do you support images", answer: "Yes! CopyBot can repost text, images, videos, polls, and clips seamlessly." },
    { question: "do you support polls", answer: "Absolutely, CopyBot supports polls along with text, photos, videos, and clips." },
    { question: "can i add multiple telegram channels", answer: "Yes, you can easily add multiple Telegram channels for reposting." },
    { question: "can i stop autoposting", answer: "Of course! You can pause or disable autoposting anytime from your dashboard." },
    { question: "how to install copybot", answer: "No installation is required! CopyBot is cloud-based and connects directly to your VK and Telegram accounts." },
    { question: "is copybot easy to use", answer: "Yes! CopyBot is designed to be super easy. No coding skills needed." },
    { question: "can i customize copybot", answer: "You can customize settings like which posts to copy, delays, and channels." },
    { question: "what is mindloop ai", answer: "MindLoop AI is the company behind CopyBot and our smart AI website chatbot." },
    { question: "do you offer customer support", answer: "Yes! Our team is ready to help you via email or Telegram." },
    { question: "how long is the free trial", answer: "The free trial lasts 7 full days, so you can test all features!" },
    { question: "is copybot safe", answer: "Yes, CopyBot uses secure APIs and encrypted connections to ensure your data is protected." },
    { question: "can i post manually", answer: "Yes, you can use CopyBot for both automatic and manual reposting." },
    { question: "what languages are supported", answer: "We currently support English, Serbian, Russian, and French!" },
    { question: "how to contact support", answer: "You can contact us at mindloop.ai.contact@gmail.com or @vkcopybot on Telegram." },
    { question: "can i schedule posts", answer: "Scheduled posting is coming soon! 🚀 Stay tuned for updates." },
    { question: "does copybot support clips", answer: "Yes, CopyBot can repost clips along with other media types." },
    { question: "is copybot available worldwide", answer: "Yes, CopyBot can be used from anywhere in the world!" },
    { question: "who made copybot", answer: "CopyBot was created by MindLoop AI Co., a team passionate about automation and AI." },
    { question: "what is a chatbot widget", answer: "A chatbot widget is a small assistant you add to your website to automate conversations and help visitors." },
    { question: "can i add your chatbot to my website", answer: "Yes! Our AI chatbot can be easily integrated into any website with just a few lines of code." },
    { question: "what does your chatbot do", answer: "Our chatbot answers customer questions instantly, provides recommendations, and improves engagement." },
    { question: "can i try the chatbot", answer: "Yes! Try our chatbot demo at mindloopaidemo.streamlit.app." },
    { question: "how to add chatbot", answer: "Adding our chatbot to your site is simple: we provide you the script and setup help if needed." },
    { question: "is the chatbot free", answer: "We offer a free version with limited features and premium plans for full capabilities." },
    { question: "is your chatbot multilingual", answer: "Yes! It supports English, Serbian, French, and Russian." },
    { question: "what platforms do you support", answer: "We support websites, e-commerce shops, and custom platforms via our API." },
    { question: "do i need coding skills", answer: "No! Our system is designed so that even non-tech users can set it up easily." },
    { question: "how fast is your chatbot", answer: "Our chatbot responds in less than a second to user questions." },
    { question: "can your chatbot recommend products", answer: "Yes! It can suggest products, services, or answer FAQs based on your business." },
    { question: "is it secure", answer: "Yes, we use industry-standard security and data protection methods." },
    { question: "can i customize responses", answer: "Yes! We can customize the chatbot responses based on your business type." },
    { question: "are there any hidden fees", answer: "No hidden fees! We believe in transparent pricing." },
    { question: "what happens after free trial", answer: "You can choose to continue with a paid plan or cancel anytime." },
    { question: "can i cancel anytime", answer: "Yes, there are no contracts. Cancel your plan anytime you want." },
    { question: "do you offer discounts", answer: "Yes! We offer discounts for yearly plans and early adopters." },
    { question: "do you work with agencies", answer: "Yes! We have special plans for agencies managing multiple clients." },
    { question: "where are your servers", answer: "Our servers are located in top data centers in Europe." },
    { question: "what is copybot", answer: "CopyBot automatically copies and posts your content from VK to Telegram, saving you time and boosting engagement." },
    { question: "how does copybot work", answer: "CopyBot monitors your VK community and automatically reposts your content to Telegram channels." },
    { question: "can copybot repost videos", answer: "Yes, CopyBot supports text, images, videos, polls, and clips." },
    { question: "is copybot free", answer: "You can try CopyBot for free for one week. Paid plans are available after the trial." },
    { question: "how to connect copybot", answer: "Just link your VK and Telegram accounts to start using CopyBot." },
    { question: "can i pause copybot", answer: "Yes, you can pause autoposting or add new channels anytime from the dashboard." },
    { question: "what types of content does copybot support", answer: "CopyBot supports text, photos, videos, polls, and clips." },
    { question: "how to integrate chatbot", answer: "Our chatbot is easy to integrate. Just paste a small script into your website's footer." },
    { question: "is copybot safe", answer: "Yes, we use encrypted connections and industry best practices to secure your data." },
    { question: "who created copybot", answer: "CopyBot is developed by MindLoop AI, specializing in AI automation solutions." },
    { question: "can i use copybot for business", answer: "Absolutely! CopyBot is perfect for businesses that want to automate content sharing." },
    { question: "how to start using copybot", answer: "Sign up, connect your VK and Telegram, and start automating in minutes!" },
    { question: "how to disable copybot temporarily", answer: "You can disable CopyBot anytime via your control panel." },
    { question: "what is mindloop ai", answer: "MindLoop AI creates smart automation tools like CopyBot and website chatbots." },
    { question: "do you offer chatbot widget", answer: "Yes, we offer a customizable chatbot widget for websites." },
    { question: "how fast does copybot repost", answer: "CopyBot reposts content within seconds of detecting a new VK post." },
    { question: "can i choose what to repost", answer: "Yes, you can filter content and select what to repost." },
    { question: "is there a free trial for chatbot", answer: "Yes, we offer a free trial for our chatbot as well." },
    { question: "can i use chatbot and copybot together", answer: "Yes, you can combine our chatbot and CopyBot for maximum automation." },
    { question: "do you support ecommerce", answer: "Yes, our bots can support e-commerce platforms and customer interaction." },
    { question: "can chatbot capture leads", answer: "Yes, our chatbot can capture leads and send them to your email or CRM." },
    { question: "how to contact support", answer: "You can contact us via email at mindloop.ai.contact@gmail.com or Telegram @vkcopybot." },
    { question: "how secure is copybot", answer: "We use secure APIs and encryption to protect your data." },
    { question: "does copybot support polls", answer: "Yes, CopyBot supports reposting polls from VK to Telegram." },
    { question: "how much does copybot cost", answer: "After the free trial, affordable monthly and yearly plans are available." },
    // ... 225 more English questions/answers similar way (randomized style)

    // Russian Questions (about 250)
    { question: "что такое copybot", answer: "CopyBot автоматически копирует и публикует ваш контент из VK в Telegram, экономя ваше время." },
    { question: "как работает copybot", answer: "CopyBot отслеживает ваше сообщество VK и мгновенно репостит посты в ваши Telegram-каналы." },
    { question: "может ли copybot репостить видео", answer: "Да, CopyBot поддерживает текст, фото, видео, опросы и клипы." },
    { question: "copybot бесплатный", answer: "Вы можете попробовать CopyBot бесплатно в течение недели. После этого доступны платные тарифы." },
    { question: "как подключить copybot", answer: "Просто свяжите свои аккаунты VK и Telegram для начала использования." },
    { question: "можно ли остановить автопостинг", answer: "Да, автопостинг можно приостановить в любое время через панель управления." },
    { question: "какие типы контента поддерживает copybot", answer: "CopyBot поддерживает текст, изображения, видео, опросы и клипы." },
    { question: "как установить чатбот", answer: "Установить наш чатбот легко — просто вставьте небольшой скрипт на ваш сайт." },
    { question: "безопасен ли copybot", answer: "Да, мы используем шифрованные соединения и защищенные API." },
    { question: "кто разработал copybot", answer: "CopyBot разработан MindLoop AI, компанией по автоматизации на базе ИИ." },
    { question: "подходит ли copybot для бизнеса", answer: "Да, CopyBot отлично подходит для автоматизации работы бизнеса." },
    { question: "как начать использовать copybot", answer: "Зарегистрируйтесь, подключите VK и Telegram, и начните автоматизировать!" },
    { question: "можно ли отключить copybot", answer: "Да, можно временно отключить CopyBot через панель управления." },
    { question: "что такое mindloop ai", answer: "MindLoop AI — компания, создающая умные решения для автоматизации." },
    { question: "есть ли у вас виджет чатбота", answer: "Да, мы предоставляем настраиваемый чатбот для сайтов." },
    { question: "насколько быстро работает copybot", answer: "CopyBot репостит контент в течение нескольких секунд после обнаружения." },
    { question: "могу ли я выбирать, что репостить", answer: "Да, вы можете фильтровать контент для репостинга." },
    { question: "есть ли бесплатная пробная версия чатбота", answer: "Да, мы также предлагаем бесплатную пробную версию нашего чатбота." },
    { question: "можно использовать чатбот и copybot вместе", answer: "Да, для максимальной автоматизации можно использовать оба решения." },
    { question: "поддерживаете ли вы электронную коммерцию", answer: "Да, наши боты могут работать с платформами электронной коммерции." },
    { question: "может ли чатбот собирать лиды", answer: "Да, чатбот может собирать контактные данные клиентов и отправлять их на вашу почту или в CRM." },
    { question: "как связаться с поддержкой", answer: "Напишите нам на mindloop.ai.contact@gmail.com или в Telegram: @vkcopybot." },
    { question: "насколько безопасен copybot", answer: "Мы используем безопасные API и шифрование для защиты данных." },
    { question: "поддерживает ли copybot опросы", answer: "Да, CopyBot поддерживает репостинг опросов из VK в Telegram." },
    { question: "сколько стоит copybot", answer: "После бесплатной недели доступны доступные ежемесячные и годовые тарифы." },
    
    { question: "what is vkcopybot", answer: "VKCopyBot is the specialized version of CopyBot optimized for VK community groups." },
    { question: "what is mindloop ai chat widget", answer: "The MindLoop AI chat widget is our interactive customer support assistant for websites." },
    { question: "how to upgrade plan", answer: "You can upgrade your plan anytime from your account dashboard." },
    { question: "how to cancel plan", answer: "Go to billing settings and click cancel plan to stop future charges." },
    { question: "hi", answer: "Hi there! 👋 I'm CopyBot and Chatbot assistant—how can I help you today?" },
    { question: "how to integrate with zapier", answer: "Use our Zapier integration to connect CopyBot with thousands of apps." },
    { question: "do you offer webhooks", answer: "Yes, you can configure webhooks to receive real-time event notifications." },
    { question: "how to use api", answer: "Check our API documentation at mindloop.ai/docs to start building integrations." },
    { question: "how long does setup take", answer: "Setup takes less than five minutes once you have your VK and Telegram tokens." },
    { question: "does copybot support group chats", answer: "Yes, CopyBot can repost to private chats, groups, and channels." },
    { question: "can i add filters", answer: "Yes, you can filter posts by keywords, hashtags, or user mentions." },
    { question: "does chat widget support images", answer: "Yes, our chat widget can handle images, links, and rich media." },
    { question: "how to track performance", answer: "Use our analytics dashboard to monitor repost counts and engagement." },
    { question: "can i white label chatbot", answer: "Our premium plans include white-labeling options for the chatbot widget." },
    { question: "does copybot have downtime", answer: "We maintain over 99.9% uptime with redundant servers in multiple regions." },
    { question: "how secure is api", answer: "Our API uses token-based authentication and HTTPS encryption for all requests." },
    { question: "can i import old posts", answer: "Yes, our import tool can backfill your posts from the last 30 days." },
    { question: "does copybot support stories", answer: "Story support is coming soon! Stay tuned for updates." },
    { question: "hey", answer: "Hey! How can I assist you with CopyBot or our Chatbot today?" },
    { question: "what is this", answer: "This is CopyBot, an automation tool that reposts your VK content to Telegram automatically." },
    { question: "how to delete account", answer: "Contact support or use the settings panel to permanently delete your account." },
    { question: "can i export chat logs", answer: "Yes, export your chat logs as CSV or JSON from the dashboard." },
    { question: "what is affiliate program", answer: "Join our affiliate program to earn commissions for referring new customers." },
    { question: "do you support slack integration", answer: "Yes, connect your Slack workspace to get notifications from CopyBot." },
    { question: "can i schedule reposts", answer: "Scheduled reposting is in beta. Request access from support." },
    { question: "what is white label", answer: "White label means you can rebrand our services as your own for clients." },
    { question: "how to give feedback", answer: "Send feedback via our in-app chat or email us at feedback@mindloop.ai." },
    { question: "what is free trial limit", answer: "The free trial includes all features with a limit of 100 reposts." },
    { question: "how to change password", answer: "Reset your password from the account settings page or via the forgot-password link." },
    { question: "does chatbot work on mobile", answer: "Yes, our chatbot widget is fully responsive and works on all devices." },
    { question: "what is system status page", answer: "Check system status at status.mindloop.ai for real-time service updates." },
    { question: "how to enable notifications", answer: "Enable desktop or email notifications in your user preferences." },
    { question: "can i use multiple vk accounts", answer: "Yes, you can link multiple VK communities to one CopyBot account." },
    { question: "what can you do", answer: "I can answer questions about CopyBot features, pricing, setup, and help troubleshoot issues." },
    { question: "what analytics do you provide", answer: "We provide repost counts, engagement rates, and top-performing posts." },
    { question: "how to set custom domain", answer: "Premium plans allow you to set a custom domain for your chatbot widget." },
    { question: "do you have sdk", answer: "We offer SDKs in JavaScript, Python, and PHP to simplify integrations." },
    { question: "how often does copybot check vk", answer: "CopyBot checks for new VK posts every 30 seconds." },
    { question: "can i mute certain users", answer: "Yes, you can mute posts from specific VK users or user IDs." },
    { question: "how to reset api key", answer: "Regenerate your API key from the API settings section in your dashboard." },
    { question: "help", answer: "Sure, I'm here to help! Ask me anything about CopyBot or our AI Chatbot." },
    { question: "can i add team members", answer: "Add team members with roles like admin or editor in your account settings." },
    { question: "what are user roles", answer: "Roles include admin, editor, and viewer with customizable permissions." },
    { question: "info", answer: "You can find more information at our website mindloop.ai or by asking me any question." },
    { question: "how to view logs", answer: "Access activity logs in the admin panel under the Logs tab." },
    { question: "can copybot handle attachments", answer: "Yes, CopyBot supports all VK attachment types including documents." },
    { question: "how to get support", answer: "Use the in-app chat or email us at support@mindloop.ai for assistance." },
    { question: "what is roadmap", answer: "View our public roadmap on Trello to see upcoming features." },
    { question: "can i use webhooks for chatbot", answer: "Yes, configure webhooks to receive chatbot events in real time." },
    { question: "hello", answer: "Hello! 👋 I'm here to help with CopyBot and Chatbot questions." },
  
    // ───────── Russian (50 items) ─────────
    { question: "что такое vkcopybot", answer: "VKCopyBot — это специальная версия CopyBot, оптимизированная для сообществ VK." },
    { question: "что такое виджет mindloop ai chat", answer: "Виджет MindLoop AI chat — это наш интерактивный помощник для поддержки клиентов на сайте." },
    { question: "как обновить тариф", answer: "Вы можете обновить тариф в любой момент на странице управления аккаунтом." },
    { question: "как отменить тариф", answer: "Перейдите в настройки оплаты и нажмите «отменить тариф», чтобы прекратить списания." },
    { question: "привет", answer: "Привет! 👋 Я ассистент CopyBot и Chatbot, чем могу помочь?" },
    { question: "как интегрировать с zapier", answer: "Используйте нашу интеграцию с Zapier для подключения CopyBot к тысячам приложений." },
    { question: "есть ли вебхуки", answer: "Да, вы можете настроить вебхуки для получения уведомлений в реальном времени." },
    { question: "как пользоваться api", answer: "Ознакомьтесь с документацией по API на mindloop.ai/docs для начала интеграции." },
    { question: "сколько времени занимает настройка", answer: "Настройка занимает менее пяти минут после получения токенов VK и Telegram." },
    { question: "поддерживает ли copybot групповые чаты", answer: "Да, CopyBot может репостить в личные чаты, группы и каналы." },
    { question: "можно ли добавить фильтры", answer: "Да, вы можете фильтровать посты по ключевым словам, хэштегам или упоминаниям." },
    { question: "поддерживает ли чат виджет изображения", answer: "Да, наш чат-виджет поддерживает изображения, ссылки и мультимедиа." },
    { question: "как отслеживать производительность", answer: "Используйте нашу панель аналитики для мониторинга количества репостов и вовлеченности." },
    { question: "можно ли белый лейбл чатбота", answer: "В премиум тарифах доступна опция белого лейбла для виджета чатбота." },
    { question: "есть ли простои у copybot", answer: "Мы обеспечиваем более 99.9% доступности с резервированием серверов в разных регионах." },
    { question: "насколько безопасен api", answer: "Наш API использует токен-аутентификацию и HTTPS шифрование для всех запросов." },
    { question: "можно ли импортировать старые посты", answer: "Да, наш инструмент импорта может добавить посты за последние 30 дней." },
    { question: "поддерживает ли copybot истории", answer: "Поддержка историй скоро появится! Следите за обновлениями." },
    { question: "здравствуйте", answer: "Здравствуйте! Я готов ответить на ваши вопросы о CopyBot и чатботе." },
    { question: "что это", answer: "Это CopyBot — инструмент автоматического репоста контента из VK в Telegram." },
    { question: "как удалить аккаунт", answer: "Свяжитесь с поддержкой или воспользуйтесь настройками, чтобы удалить аккаунт навсегда." },
    { question: "можно ли экспортировать логи чата", answer: "Да, вы можете экспортировать логи чата в CSV или JSON из панели." },
    { question: "что такое партнерская программа", answer: "Присоединяйтесь к партнерской программе и зарабатывайте комиссионные за привлечение клиентов." },
    { question: "поддерживаете ли вы slack интеграцию", answer: "Да, подключите Slack для получения уведомлений от CopyBot." },
    { question: "можно ли планировать репосты", answer: "Функция планирования в бета-тестировании, запросите доступ у поддержки." },
    { question: "что такое white label", answer: "White label позволяет брендингово оформить наши сервисы как ваши собственные." },
    { question: "как оставить отзыв", answer: "Отправьте отзыв через встроенный чат или по электронной почте feedback@mindloop.ai." },
    { question: "какие ограничения у пробной версии", answer: "Пробная версия включает все функции с лимитом в 100 репостов." },
    { question: "как сменить пароль", answer: "Сбросьте пароль в настройках аккаунта или через ссылку «забыли пароль»." },
    { question: "работает ли чатбот на мобильных", answer: "Да, виджет чатбота адаптивен и работает на любых устройствах." },
    { question: "где страница статуса системы", answer: "Статус системы доступен на status.mindloop.ai для актуальной информации." },
    { question: "как включить уведомления", answer: "Включите уведомления на рабочем столе или по электронной почте в настройках." },
    { question: "можно ли использовать несколько vk аккаунтов", answer: "Да, вы можете привязать несколько сообществ VK к одному аккаунту CopyBot." },
    { question: "чем ты можешь помочь", answer: "Я могу ответить на вопросы о функциях CopyBot, ценах, настройке и устранении проблем." },
    { question: "какая аналитика доступна", answer: "Мы предоставляем статистику репостов, уровень вовлеченности и топовые посты." },
    { question: "как установить свой домен", answer: "В премиум тарифах вы можете настроить собственный домен для чатбота." },
    { question: "есть ли sdk", answer: "Мы предлагаем SDK на JavaScript, Python и PHP для упрощения интеграций." },
    { question: "как часто copybot проверяет vk", answer: "CopyBot проверяет новые посты VK каждые 30 секунд." },
    { question: "можно ли игнорировать определенных пользователей", answer: "Да, вы можете игнорировать посты от определенных пользователей VK." },
    { question: "как сбросить api ключ", answer: "Перегенерируйте API ключ в разделе настроек API на панели управления." },
    { question: "помощь", answer: "Конечно, я здесь, чтобы помочь! Задавайте любые вопросы о CopyBot или нашему чатботу." },
    { question: "можно ли добавить участников команды", answer: "Добавьте участников команды с ролями админа или редактора в настройках аккаунта." },
    { question: "какие есть роли пользователей", answer: "Роли включают админа, редактора и зрителя с настраиваемыми правами." },
    { question: "инфо", answer: "Больше информации на сайте mindloop.ai или задайте мне любой вопрос." },
    { question: "как просмотреть логи", answer: "Доступ к журналам активности находится во вкладке «Логи» в админ-панели." },
    { question: "поддерживает ли copybot вложения", answer: "Да, CopyBot поддерживает все типы вложений VK, включая документы." },
    { question: "как получить поддержку", answer: "Используйте встроенный чат или напишите нам на support@mindloop.ai." },
    { question: "какой у вас roadmap", answer: "Просмотрите наш публичный roadmap на Trello, чтобы узнать о будущих функциях." },
    { question: "можно ли использовать вебхуки для чатбота", answer: "Да, настройте вебхуки, чтобы получать события чатбота в реальном времени." },
    { question: "добрый день", answer: "Добрый день! Я готов помочь с вопросами о CopyBot и чатботе." },// ... 225 more Russian questions/answers similar way (randomized style)

      // ───────── English (50 items) ─────────
  { question: "does copybot support GIFs", answer: "Yes, CopyBot supports reposting GIFs along with images and other media." },
  { question: "can i set custom delays between reposts", answer: "Yes, you can configure minimum and maximum delays between reposts in the settings." },
  { question: "how to whitelist users", answer: "Use the whitelist feature in the dashboard to allow reposts only from specific VK users." },
  { question: "what logging does copybot provide", answer: "CopyBot logs every repost attempt with timestamps, post IDs, and status codes for debugging." },
  { question: "is there a mobile app for copybot", answer: "Not yet—CopyBot is accessible via a responsive web dashboard on mobile devices." },
  { question: "how to embed chat widget", answer: "Copy the embed snippet from the Dashboard’s Embed section and paste it into your site’s HTML." },
  { question: "can i integrate chatbot with wordpress", answer: "Yes, install our WordPress plugin or paste the JS snippet into your theme’s header." },
  { question: "does chat widget support video calls", answer: "Video calls aren’t supported yet; currently we offer text and image messaging only." },
  { question: "how to enable spam protection", answer: "Enable anti-spam filters under Security → Spam Protection in the dashboard." },
  { question: "what is GDPR compliance", answer: "GDPR compliance means we handle personal data according to EU regulations, with user consent and data deletion policies." },
  { question: "does copybot comply with GDPR", answer: "Yes, CopyBot is fully GDPR-compliant and stores all data on EU-based servers." },
  { question: "can i restrict posting hours", answer: "Yes, set allowed repost windows (days and times) under Schedule settings." },
  { question: "how to get webhook secret", answer: "Find your webhook secret token in Integrations → Webhooks in the dashboard." },
  { question: "can i set retry policy", answer: "Yes, configure retry attempts and intervals in Advanced → Error Handling." },
  { question: "how to handle errors", answer: "Enable error notifications via email or webhook and review the logs for details." },
  { question: "does chat widget support voice messages", answer: "Not yet; we plan to support voice messages in an upcoming release." },
  { question: "can chatbot use AI for sentiment analysis", answer: "Yes, our AI can analyze sentiment and tag messages as positive, neutral, or negative." },
  { question: "what AI engine is used", answer: "We use OpenAI’s GPT-4 for natural language understanding and response generation." },
  { question: "how to set fallback messages", answer: "Configure default fallback responses under Chatbot → Settings → Fallback." },
  { question: "can chatbot escalate to human", answer: "Yes, enable the Live Chat Handoff option to transfer conversations to your team." },
  { question: "how to train chatbot", answer: "Upload FAQ content or chat logs in the Training section of the Chatbot dashboard." },
  { question: "does chatbot support NLP", answer: "Yes, our chatbot uses advanced NLP to understand user intent and context." },
  { question: "what languages does NLP support", answer: "NLP currently supports English, Russian, French, and Serbian, with more coming soon." },
  { question: "how to update chatbot responses", answer: "Edit response templates in Chatbot → Responses on your dashboard." },
  { question: "can chatbot collect feedback", answer: "Yes, enable post-chat feedback prompts to collect user ratings and comments." },
  { question: "does chat widget support forms", answer: "Yes, you can embed custom forms into the chat flow to collect user data." },
  { question: "how to build chatbot flow", answer: "Use the visual Flow Builder in the dashboard to design conversation paths." },
  { question: "what messaging platforms are supported", answer: "We support Telegram, VK, WhatsApp, Facebook Messenger, and custom web chats." },
  { question: "can copybot use proxies", answer: "Yes, specify HTTP/S proxy settings in Advanced → Network Settings." },
  { question: "how to handle rate limits", answer: "CopyBot auto-queues requests and backs off on HTTP 429 errors." },
  { question: "does copybot use caching", answer: "Yes, content is cached for a configurable duration to reduce API calls." },
  { question: "what database is used", answer: "We use PostgreSQL for data storage and Redis for caching and queues." },
  { question: "can i self-host copybot", answer: "Self-hosting is available on enterprise plans—contact sales for details." },
  { question: "is there an on-prem version", answer: "Yes, we offer an on-prem Docker deployment for enterprise customers." },
  { question: "how to request self-host deployment", answer: "Email sales@mindloop.ai with your requirements to get started." },
  { question: "does chatbot support OAuth", answer: "Yes, you can authenticate users via OAuth providers like Google and Facebook." },
  { question: "how to secure APIs", answer: "Use API keys, HTTPS/TLS, and IP whitelisting for maximum security." },
  { question: "what encryption is used", answer: "We use AES-256 for data at rest and TLS 1.2+ for data in transit." },
  { question: "can i customize widget CSS", answer: "Yes, add custom CSS rules in Chatbot → Custom Styling." },
  { question: "how to translate widget text", answer: "Edit localization strings or upload translation files under Localization." },
  { question: "does copybot support scheduled posting by day", answer: "Yes, choose specific weekdays and times for each repost schedule." },
  { question: "can i tag posts on repost", answer: "Enable tagging and define default tags under Advanced → Tags." },
  { question: "does copybot support hashtags", answer: "Yes, automatically add or filter by hashtags in the Hashtag settings." },
  { question: "can i filter by author", answer: "Whitelist or blacklist posts based on VK author IDs in Filters." },
  { question: "does chatbot support rich cards", answer: "Yes, send interactive cards with images, titles, and buttons." },
  { question: "how to debug integration issues", answer: "Use the Debug Console in Advanced settings and check the real-time logs." },
  { question: "can i use webhook for repost failures", answer: "Yes, configure failure webhooks under Integrations → Webhooks." },
  { question: "does copybot send email alerts", answer: "Enable email alerts for important events under Notifications." },
  { question: "can i disable notifications", answer: "Toggle notification types on or off in Profile → Notification Preferences." },
  { question: "what timezone does copybot use", answer: "Default is UTC; you can set your local timezone in Account Settings." },

  { question: "поддерживает ли copybot GIF-файлы", answer: "Да, CopyBot может репостить GIF-файлы вместе с другими медиа." },
  { question: "могу ли я установить задержку между репостами", answer: "Да, в настройках можно указать минимальную и максимальную задержку." },
  { question: "как добавить пользователей в белый список", answer: "Используйте функцию «Белый список» в панели управления для указания разрешённых пользователей." },
  { question: "какую статистику ведёт copybot", answer: "CopyBot записывает время, ID поста и статус каждого репоста для отладки." },
  { question: "есть ли мобильное приложение copybot", answer: "Пока нет — используйте адаптивную веб-версию на мобильных устройствах." },
  { question: "как встроить виджет чата", answer: "Скопируйте код из раздела «Embed» и вставьте его в HTML вашего сайта." },
  { question: "можно ли интегрировать чатбот с wordpress", answer: "Да, установите наш плагин или вставьте JS-код в header темы." },
  { question: "поддерживает ли виджет видео-звонки", answer: "Видео-звонки пока не поддерживаются, только текст и изображения." },
  { question: "как включить защиту от спама", answer: "Включите антиспам-фильтры в разделе «Безопасность» → «Защита от спама»." },
  { question: "что такое соответствие GDPR", answer: "Это соблюдение правил ЕС по обработке персональных данных с согласием пользователей." },
  { question: "соответствует ли copybot GDPR", answer: "Да, мы полностью соответствуем GDPR и храним данные на серверах в ЕС." },
  { question: "могу ли я ограничить часы публикации", answer: "Да, задайте допустимые окна репостов (дни и время) в настройках расписания." },
  { question: "как получить секрет вебхука", answer: "Ваш секретный токен находится в «Интеграции» → «Вебхуки»." },
  { question: "могу ли я задать политику повторных попыток", answer: "Да, настройте количество попыток и интервалы в «Расширенные» → «Обработка ошибок»." },
  { question: "как обрабатывать ошибки", answer: "Включите уведомления об ошибках по email или вебхуку и изучите логи." },
  { question: "поддерживает ли чатбот голосовые сообщения", answer: "Пока нет, но мы планируем добавить эту функцию в следующих обновлениях." },
  { question: "может ли чатбот анализировать тональность", answer: "Да, наш ИИ определяет тональность и маркирует сообщения как положительные, нейтральные или отрицательные." },
  { question: "какой движок ИИ используется", answer: "Мы используем GPT-4 от OpenAI для понимания и генерации ответов." },
  { question: "как настроить сообщения при ошибке", answer: "Настройте стандартные ответы на ошибки в «Чатбот» → «Настройки» → «Fallback»." },
  { question: "может ли чатбот передавать на оператора", answer: "Да, включите опцию «Live Chat Handoff» для передачи диалога агенту." },
  { question: "как обучить чатбот", answer: "Загрузите FAQ или логи чатов в разделе «Обучение» панели управления." },
  { question: "поддерживает ли чатбот NLP", answer: "Да, мы используем NLP для понимания намерений и контекста пользователей." },
  { question: "какие языки поддерживает NLP", answer: "NLP поддерживает английский, русский, французский и сербский." },
  { question: "как обновить ответы чатбота", answer: "Редактируйте шаблоны ответов на странице «Чатбот» → «Ответы»." },
  { question: "может ли чатбот собирать отзывы", answer: "Да, включите пост-чат-опросы для оценки и комментариев пользователей." },
  { question: "поддерживает ли виджет формы", answer: "Да, в чат можно встроить формы для сбора данных." },
  { question: "как создать сценарий чатбота", answer: "Используйте визуальный конструктор сценариев в панели управления." },
  { question: "какие мессенджеры поддерживаются", answer: "Поддерживаются Telegram, VK, WhatsApp, Facebook Messenger и веб-чат." },
  { question: "может ли copybot использовать прокси", answer: "Да, укажите HTTP/S прокси в «Расширенные» → «Сеть»." },
  { question: "как обрабатывать ограничения скорости", answer: "CopyBot автоматически ставит запросы в очередь и делает паузу при HTTP 429." },
  { question: "использует ли copybot кэширование", answer: "Да, содержимое кешируется на заданный период, чтобы снизить нагрузку на API." },
  { question: "какая СУБД используется", answer: "Мы используем PostgreSQL для данных и Redis для кеша и очередей." },
  { question: "могу ли я развернуть copybot локально", answer: "Локальное развёртывание доступно на корпоративных тарифах — свяжитесь с sales@mindloop.ai." },
  { question: "есть ли версия для локального размещения", answer: "Да, мы предлагаем on-premise Docker-развертывание для предприятий." },
  { question: "как запросить локальное развёртывание", answer: "Отправьте письмо на sales@mindloop.ai с описанием ваших требований." },
  { question: "поддерживает ли чатбот OAuth", answer: "Да, можно аутентифицировать пользователей через OAuth-провайдеров." },
  { question: "как обеспечить безопасность API", answer: "Используйте API-ключи, HTTPS/TLS и белый список IP-адресов." },
  { question: "какое шифрование используется", answer: "Для хранения данных — AES-256, для передачи — TLS 1.2+." },
  { question: "могу ли я настраивать CSS виджета", answer: "Да, добавьте свои CSS-правила в «Чатбот» → «Custom Styling»." },
  { question: "как перевести текст виджета", answer: "Отредактируйте локализационные строки или загрузите файлы перевода." },
  { question: "поддерживает ли copybot плановые публикации по дням", answer: "Да, выберите нужные дни недели и время для каждого расписания." },
  { question: "могу ли я добавлять теги к постам", answer: "Включите теги и укажите значения в «Расширенные» → «Теги»." },
  { question: "поддерживает ли copybot хэштеги", answer: "Да, автоматически добавляйте или фильтруйте по хэштегам." },
  { question: "могу ли я фильтровать по автору", answer: "Используйте белый и чёрный списки авторов по их VK-ID." },
  { question: "поддерживает ли чатбот rich-карты", answer: "Да, отправляйте интерактивные карты с изображениями, заголовками и кнопками." },
  { question: "как отладить интеграцию", answer: "Откройте Debug Console в настройках и смотрите логи в реальном времени." },
  { question: "можно ли использовать вебхук для ошибок репоста", answer: "Да, настройте вебхук ошибок в «Интеграции» → «Вебхуки»." },
  { question: "отправляет ли copybot уведомления по email", answer: "Включите email-уведомления в разделе «Уведомления»." },
  { question: "могу ли я отключить уведомления", answer: "Выключите ненужные уведомления в «Профиль» → «Настройки уведомлений»." },
  { question: "какой часовой пояс использует copybot", answer: "По умолчанию UTC; можно установить местный часовой пояс в настройках аккаунта." },
  { question: "cao", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "hez", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "yo", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "sup", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "whatsup", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "heyo", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "hey bot", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "hey copybot", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "allo", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "hola", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "ciao", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "bonjour", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "ahoj", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "hey there", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  { question: "what?", answer: "Hey! How can I help you today? Are you interested in CopyBot, our AI Chatbot, or something else?" },
  {question: "здарова", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "приветик", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "здрасьте", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "алло", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "хай", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "хелло", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "йо", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "что?", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "?", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "??", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "его", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "шо", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "прив", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "эй бот", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "че", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "здарова", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "приветик", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "здрасьте", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "алло", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "хай", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "хелло", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "йо", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "что?", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "?", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "??", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "его", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "шо", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "прив", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "эй бот", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },
  { question: "че", answer: "Привет! Чем могу помочь сегодня? Вас интересует CopyBot, наш AI-чатбот или что-то другое?" },

  // CopyBot specific
{ question: "why use copybot", answer: "CopyBot saves you hours by automatically reposting your VK content to Telegram. No more manual work!" },
{ question: "is copybot worth it", answer: "Yes! CopyBot increases your reach and engagement while freeing up your time for important tasks." },
{ question: "what is copybot for", answer: "CopyBot helps you manage VK and Telegram together without needing extra staff." },

// Chatbot specific
{ question: "why use chatbot", answer: "Our AI Chatbot answers client questions instantly, improves customer experience, and works 24/7 for you." },
{ question: "is chatbot worth it", answer: "Yes! The chatbot boosts conversions, saves you time, and provides instant support to every visitor." },
{ question: "what is chatbot for", answer: "The chatbot automates customer communication, helping businesses handle more clients without extra work." },

// General
{ question: "why would i do it", answer: "Because automating tasks with CopyBot or Chatbot saves time, increases efficiency, and grows your business." },
{ question: "is it worth using mindloop ai", answer: "Definitely! Our solutions help you stay ahead of competitors by automating routine work smartly." },
{ question: "how can mindloop help me", answer: "We offer automation tools like CopyBot and Chatbots to save you time, boost customer satisfaction, and scale faster." },

// CopyBot specific
{ question: "зачем нужен copybot", answer: "CopyBot экономит ваше время, автоматически репостя контент из VK в Telegram без ручной работы!" },
{ question: "copybot стоит того", answer: "Да! CopyBot увеличивает охваты, вовлеченность и освобождает время для важных задач." },
{ question: "для чего нужен copybot", answer: "CopyBot позволяет управлять VK и Telegram одновременно без необходимости нанимать дополнительный персонал." },

// Chatbot specific
{ question: "зачем нужен чатбот", answer: "Наш AI-чатбот мгновенно отвечает клиентам, улучшает их опыт и работает для вас 24/7 без перерывов." },
{ question: "стоит ли использовать чатбот", answer: "Определённо! Чатбот увеличивает продажи, экономит время и улучшает поддержку клиентов." },
{ question: "для чего нужен чатбот", answer: "Чатбот автоматизирует общение с клиентами, помогая бизнесу обслуживать больше запросов без дополнительных ресурсов." },

{ question: "Do you speak English", answer: "yes, I do." },
{ question: "English", answer: "yes?" },
{ question: "speak in english", answer: "okay!"},
{ question: "and tell me about AI assistant", answer: "Our AI Chatbot answers client questions instantly, improves customer experience, and works 24/7 for you." },
{ question: "what is copybot", answer: "CopyBot automatically reposts your VK content to your Telegram channels, saving you time and boosting engagement." },
{ question: "tell me about copybot", answer: "CopyBot helps automate posting from VK to Telegram, so you don't have to do it manually." },
{ question: "how does copybot help me", answer: "CopyBot saves hours every week by posting for you and increasing your audience reach." },
{ question: "is copybot automatic", answer: "Yes! CopyBot automatically monitors your VK and reposts new content to Telegram." },
{ question: "what problems does copybot solve", answer: "CopyBot eliminates the need for manual copying and posting between platforms." },
{ question: "can copybot save my time", answer: "Absolutely! With CopyBot, you no longer waste time managing two networks manually." },
{ question: "why do people use copybot", answer: "Because it simplifies content management and increases channel engagement easily." },
{ question: "is copybot worth it", answer: "Yes! CopyBot is an affordable way to automate routine tasks and grow your Telegram audience." },
{ question: "how to get started with copybot", answer: "Just connect your VK and Telegram accounts — setup takes just a few minutes!" },
{ question: "do i need coding skills for copybot", answer: "No coding needed! CopyBot is ready to use out of the box." },
{ question: "copybot", answer: "CopyBot automatically reposts your VK content to your Telegram channels, saving you time and boosting engagement." },


{ question: "what is ai assistant", answer: "Our AI Assistant is a smart chatbot that answers client questions instantly and works 24/7 for you." },
{ question: "i wanna know about ai assistant", answer: "Our AI Assistant boosts engagement, improves support quality, and reduces your workload." },
{ question: "tell me about the chatbot", answer: "The chatbot (AI Assistnat) instantly answers FAQs, helps clients, and improves their experience on your website." },
{ question: "how does ai assistant help", answer: "It provides immediate answers to visitors, increases satisfaction, and captures more leads." },
{ question: "is the chatbot smart", answer: "Yes! It uses advanced AI and NLP to understand and answer user questions naturally." },
{ question: "why should i use ai assistant", answer: "Because it saves time, improves customer experience, and works even when your team is offline." },
{ question: "can chatbot work without me", answer: "Yes, the AI assistant handles communication automatically, even when you're away." },
{ question: "is the chatbot easy to install", answer: "Very easy! Just paste a short script on your site — no coding needed." },
{ question: "does ai assistant support multiple languages", answer: "Yes! It supports English, Serbian, Russian, and French." },
{ question: "is ai assistant available 24/7", answer: "Yes! Your AI Assistant is always online, ready to engage with visitors day and night." },
{ question: "I wanna know more about chatbot", answer: "Yes! Your AI Assistant is always online, ready to engage with visitors day and night." },
{ question: "I wanna know more about AI assistant", answer: "Yes! Your AI Assistant is always online, ready to engage with visitors day and night." },
{ question: "ai assistant", answer: "Our AI Assistant is a smart chatbot that answers client questions instantly and works 24/7 for you." },

// General
{ question: "зачем мне это", answer: "Автоматизация с помощью CopyBot и Chatbot экономит время, увеличивает эффективность и помогает бизнесу расти." },
{ question: "стоит ли использовать mindloop ai", answer: "Конечно! Наши решения позволяют опережать конкурентов, автоматизируя рутинные задачи." },
{ question: "как mindloop может помочь мне", answer: "MindLoop AI предлагает инструменты автоматизации — CopyBot и чатботы — для экономии времени и роста бизнеса." }


];
  
  export default faqData;
  